site_url: "https://chatgpt-pythoncode.github.io/EoGuide2/"
search: false

backend:
  name: github
  repo: ChatGPT-PythonCode/EoGuide2
  branch: main
  base_url: https://eoguide2.tronnfts.workers.dev

media_folder: "EoGuide2/client/public/uploads"
public_folder: "/EoGuide2/uploads"

collections:
  - name: "guides"
    label: "Guides"
    folder: "EoGuide2/content/guides"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["quest", "travel", "class", "command", "misc"]
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Header Image", name: "imageUrl", widget: "image", required: false }
      - { label: "Video URL (YouTube/Vimeo)", name: "videoUrl", widget: "string", required: false }
      - { label: "Created At", name: "createdAt", widget: "datetime", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
